import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  welcomeStyle from '../styles/welcome.module.css'
import Button from 'react-bootstrap/Button';
import Link from "next/link";
import axios from "axios";
import {ToastContainer, toast} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {useState} from "react";
import Router from "next/router";
import 'react-loading-skeleton/dist/skeleton.css'
import Skeleton from "react-loading-skeleton";

export default function Home() {
const [mess_id,setMessId]=useState('');
    const [loading,setLoading]=useState(false);
    const Join=async ()=>{
        await axios.post("http://localhost:5000/mess/join-mess",{
            mess_id
        },{headers: {'Accept': 'application/json',
                'Content-Type': 'application/json',
                Authorization: `Bearer ${localStorage.getItem('access_token')}`}})
            .then((data)=>{

                if(data.data.status==404){
                    toast.error(data.data.msg)
                }else{
                    localStorage.setItem('mess_id',data.data.mess_id);
                    Router.push({
                        pathname: '/statement',
                        query: { mess_id: data.data.mess_id }
                    });
                }
            }).catch(err=>{
                toast.error(err.response.data.msg[0]);
            })
    }
    return (
        <div>
            {!loading ?
                <div className={welcomeStyle.container}>

                    <Head>
                        <title>Create a Mess</title>
                        <meta name="description" content="Generated by create next app"/>
                        <link rel="icon" href="/favicon.ico"/>
                    </Head>

                    <main className={welcomeStyle.main}>
                        <h5 className={welcomeStyle.title}>
                            Welcome to <a href="#">MESS APP</a>
                        </h5>

                        <Link href={'/createmess'}>
                            <Button className={welcomeStyle.create_mess_button} variant={"outline-primary"} >Create A Mess</Button>
                        </Link>

                        <span >
              <input  className={welcomeStyle.input} placeholder={'Enter Mess Id'} type="text" name={"mess_name"}
                     onChange={(e) => {
                         setMessId(e.target.value);
                     }}/>
               <button  className={welcomeStyle.join_button} type={'button'} onClick={() => Join()}> Join </button>
                     <ToastContainer
                         position="top-right"
                         autoClose={5000}
                         hideProgressBar={false}
                         newestOnTop={false}
                         closeOnClick
                         rtl={false}
                         pauseOnFocusLoss
                         draggable
                         pauseOnHover
                     />
          </span>


                    </main>

          {/*          <footer className={styles.footer}>*/}
          {/*              <a*/}
          {/*                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
          {/*                  target="_blank"*/}
          {/*                  rel="noopener noreferrer"*/}
          {/*              >*/}
          {/*                  Mess Meal Managemant{' '}*/}
          {/*                  <span className={styles.logo}>*/}
          {/*  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>*/}
          {/*</span>*/}
          {/*              </a>*/}
          {/*          </footer>*/}
                </div> : <Skeleton/>
            }
        </div>
    )
}



